gantsign/ansible-role-golang

README.md, meta/main.yml, molecule.yml
Updated docs, metadata and Molecule tests.
=> Added support for Debian and Enterprise Linux

README.md, defaults/main.yml, tests/test_role.py, vars/versions/1.7.4.yml
1.7.4 will now be installed by default.
=> Updated Go to 1.7.4

README.md, defaults/main.yml, tests/test_role.py, vars/versions/1.8.yml
1.8 will now be installed by default.
=> Updated Go to 1.8

README.md, defaults/main.yml, tests/test_role.py, vars/versions/1.8.1.yml
1.8.1 will now be installed by default.
=> Updated Go to 1.8.1

README.md, defaults/main.yml, tests/test_role.py, vars/versions/1.8.2.yml
1.8.2 will now be installed by default.
=> Updated Go to 1.8.2

README.md, defaults/main.yml, tests/test_role.py, vars/versions/1.8.3.yml
1.8.3 will now be installed by default.
Enhancement: resolves #17
=> Updated Go to 1.8.3

README.md, defaults/main.yml, tests/test_role.py, vars/versions/1.9.yml
1.9 will now be installed by default.
=> Updated Go to 1.9

README.md, defaults/main.yml, tests/test_role.py, vars/versions/1.9.1.yml
1.9.1 will now be installed by default.
=> Updated Go to 1.9.1

README.md, defaults/main.yml, tests/test_role.py, vars/versions/1.9.2.yml
1.9.2 will now be installed by default.
=> Updated Go to 1.9.2

README.md, defaults/main.yml, tests/test_role.py, vars/versions/1.9.3.yml
1.9.3 will now be installed by default.
=> Updated Go to 1.9.3

README.md, defaults/main.yml, tests/test_role.py, vars/versions/1.9.4.yml
1.9.4 will now be installed by default.
=> Updated Go to 1.9.4

README.md, defaults/main.yml, tests/test_role.py, vars/versions/1.10.yml
1.10 will now be installed by default.
=> Updated Go to 1.10

.travis.yml, meta/main.yml
In preparation for switching to Molecule 2.
=> Increased minimum Ansible version to 2.3

.travis.yml, molecule/centos-6/Dockerfile.j2, molecule/centos-6/INSTALL.rst, molecule/centos-6/molecule.yml, molecule/centos-7/Dockerfile.j2, molecule/centos-7/INSTALL.rst, molecule/centos-7/molecule.yml, molecule/debian-jessie/Dockerfile.j2, molecule/debian-jessie/INSTALL.rst, molecule/debian-jessie/molecule.yml, molecule/debian-wheezy/Dockerfile.j2, molecule/debian-wheezy/INSTALL.rst, molecule/debian-wheezy/molecule.yml, molecule/default/molecule.yml, molecule/ubuntu-trusty/Dockerfile.j2, molecule/ubuntu-trusty/INSTALL.rst, molecule/ubuntu-trusty/molecule.yml
For improved build time and reliability.
=> Changed to use build matrix for Linux distributions

README.md, meta/main.yml, molecule/fedora-27/Dockerfile.j2, molecule/fedora-27/INSTALL.rst, molecule/fedora-27/molecule.yml
* Added to test matrix
* Added to metadata
* Added to README
=> Added support for Fedora 27

.travis.yml, README.md, molecule/default/playbook.yml, molecule/opensuse-leap/Dockerfile.j2, molecule/opensuse-leap/INSTALL.rst, molecule/opensuse-leap/molecule.yml, tasks/main.yml
* Added to test matrix
* Added to README
=> Added support for openSUSE Leap

tasks/main.yml
Avoid unnecessary escape sequence processing.
=> Switched to single quoted strings in YAML

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.10.3.yml
1.10.3 will now be installed by default.
=> Updated Go to 1.10.3

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.11.yml
1.11 will now be installed by default.
=> Updated Go to 1.11

molecule/centos-6/molecule.yml, molecule/centos-7/molecule.yml, molecule/debian-stretch/molecule.yml, molecule/debian-wheezy/molecule.yml, molecule/fedora-27/molecule.yml, molecule/opensuse-leap/molecule.yml, molecule/ubuntu-trusty/molecule.yml
Removed unnecessary trailing slash.
=> Fixed location of Molecule tests

README.md, meta/main.yml, molecule/fedora/molecule.yml
=> Upgraded Fedora version to 28

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.11.1.yml
1.11.1 will now be installed by default.
=> Updated Go to 1.11.1

README.md
=> Restored 1.11 to documentation

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.11.2.yml
1.11.2 will now be installed by default.
=> Updated Go to 1.11.2

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.11.3.yml
1.11.3 will now be installed by default.
=> Updated Go to 1.11.3

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.11.4.yml
1.11.4 will now be installed by default.
=> Updated Go to 1.11.4

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.11.5.yml
1.11.5 will now be installed by default.
=> Updated Go to 1.11.5

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.12.yml
1.12 will now be installed by default.
=> Updated Go to 1.12

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.12.1.yml
1.12.1 will now be installed by default.
=> Updated Go to 1.12.1

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.12.2.yml
1.12.2 will now be installed by default.
=> Updated Go to 1.12.2

.travis.yml, molecule/ubuntu-max-go-eol/INSTALL.rst, molecule/ubuntu-max-go-eol/molecule.yml, molecule/ubuntu-max-go-eol/playbook.yml, molecule/ubuntu-max-go-eol/tests/test_role.py
Go maintains two minor releases at a time.
=> Added test for Go EOL release

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.12.3.yml
1.12.3 will now be installed by default.
=> Updated Go to 1.12.3

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.12.4.yml
1.12.4 will now be installed by default.
=> Updated Go to 1.12.4

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.12.5.yml
1.12.5 will now be installed by default.
=> Updated Go to 1.12.5

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.12.6.yml
1.12.6 will now be installed by default.
=> Updated Go to 1.12.6

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.12.7.yml
1.12.7 will now be installed by default.
=> Updated Go to 1.12.7

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.12.8.yml
1.12.8 will now be installed by default.
=> Updated Go to 1.12.8

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.12.9.yml
1.12.9 will now be installed by default.
=> Updated Go to 1.12.9

README.md, defaults/main.yml, molecule/default/tests/test_role.py, molecule/ubuntu-max-go-eol/playbook.yml, molecule/ubuntu-max-go-eol/tests/test_role.py, vars/versions/1.13.yml
1.13 will now be installed by default.
=> Updated Go to 1.13

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.13.1.yml
1.13.1 will now be installed by default.
=> Updated Go to 1.13.1

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.13.2.yml
1.13.2 will now be installed by default.
=> Updated Go to 1.13.2

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.13.3.yml
1.13.3 will now be installed by default.
=> Updated Go to 1.13.3

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.13.4.yml
1.13.4 will now be installed by default.
=> Updated Go to 1.13.4

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.13.5.yml
1.13.5 will now be installed by default.
=> Updated Go to 1.13.5

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.13.6.yml
1.13.6 will now be installed by default.
=> Updated Go to 1.13.6

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.13.7.yml
1.13.7 will now be installed by default.
=> Updated Go to 1.13.7

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.13.8.yml
1.13.8 will now be installed by default.
=> Updated Go to 1.13.8

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.14.yml
1.14 will now be installed by default.
=> Updated Go to 1.14

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.14.1.yml
1.14.1 will now be installed by default.
=> Updated Go to 1.14.1

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.14.2.yml
1.14.2 will now be installed by default.
=> Updated Go to 1.14.2

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.14.3.yml
1.14.3 will now be installed by default.
=> Updated Go to 1.14.3

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.14.4.yml
1.14.4 will now be installed by default.
=> Updated Go to 1.14.4

.travis.yml
=> Added tests for arm64

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.14.5-aarch64.yml, vars/versions/1.14.5.yml
1.14.5 will now be installed by default.
=> Updated Go to 1.14.5

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.14.6-aarch64.yml, vars/versions/1.14.6.yml
1.14.6 will now be installed by default.
=> Updated Go to 1.14.6

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.14.7-aarch64.yml, vars/versions/1.14.7.yml
1.14.7 will now be installed by default.
=> Updated Go to 1.14.7

.travis.yml
Keeping up with the latest changes.
=> Updated Python to 3.6

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.15.1-aarch64.yml, vars/versions/1.15.1.yml
1.15.1 will now be installed by default.
=> Updated Go to 1.15.1

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.15.2-aarch64.yml, vars/versions/1.15.2.yml
1.15.2 will now be installed by default.
=> Updated Go to 1.15.2

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.15.3-aarch64.yml, vars/versions/1.15.3.yml
1.15.3 will now be installed by default.
=> Updated Go to 1.15.3

README.md
So users can view the build details.
=> Linked GitHub Actions badge

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.15.4-arm64.yml, vars/versions/1.15.4-armv6l.yml, vars/versions/1.15.4.yml
1.15.4 will now be installed by default.
=> Updated Go to 1.15.4

.github/workflows/release.yml
=> Fixed GitHub Actions Ansible role import

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.15.5-arm64.yml, vars/versions/1.15.5-armv6l.yml, vars/versions/1.15.5.yml
1.15.5 will now be installed by default.
=> Updated Go to 1.15.5

README.md, meta/main.yml, molecule/centos-max/molecule.yml
=> Verify CentOS version 8 compatibility

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.15.6-arm64.yml, vars/versions/1.15.6-armv6l.yml, vars/versions/1.15.6.yml
1.15.6 will now be installed by default.
=> Updated Go to 1.15.6

.github/workflows/ci.yml, .github/workflows/release.yml
* Add test-all job
* Make Ansible install more efficient
=> GitHub Actions improvements

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.15.7-arm64.yml, vars/versions/1.15.7-armv6l.yml, vars/versions/1.15.7.yml
1.15.7 will now be installed by default.
=> Updated Go to 1.15.7

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.15.8-arm64.yml, vars/versions/1.15.8-armv6l.yml, vars/versions/1.15.8.yml
1.15.8 will now be installed by default.
=> Updated Go to 1.15.8

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.16-arm64.yml, vars/versions/1.16-armv6l.yml, vars/versions/1.16.yml
1.16 will now be installed by default.
=> Updated Go to 1.16

README.md, meta/main.yml, molecule/debian-max/molecule.yml
Buster is the latest stable version of Debian.
=> Increased upper Debian test version to Buster

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.16.1-arm64.yml, vars/versions/1.16.1-armv6l.yml, vars/versions/1.16.1.yml
1.16.1 will now be installed by default.
=> Updated Go to 1.16.1

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.16.2-arm64.yml, vars/versions/1.16.2-armv6l.yml, vars/versions/1.16.2.yml
1.16.2 will now be installed by default.
=> Updated Go to 1.16.2

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.16.3-arm64.yml, vars/versions/1.16.3-armv6l.yml, vars/versions/1.16.3.yml
1.16.3 will now be installed by default.
=> Updated Go to 1.16.3

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.16.4-arm64.yml, vars/versions/1.16.4-armv6l.yml, vars/versions/1.16.4.yml
1.16.4 will now be installed by default.
=> Updated Go to 1.16.4

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.16.5-arm64.yml, vars/versions/1.16.5-armv6l.yml, vars/versions/1.16.5.yml
1.16.5 will now be installed by default.
=> Updated Go to 1.16.5

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.16.6-arm64.yml, vars/versions/1.16.6-armv6l.yml, vars/versions/1.16.6.yml
1.16.6 will now be installed by default.
=> Updated Go to 1.16.6

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.16.7-arm64.yml, vars/versions/1.16.7-armv6l.yml, vars/versions/1.16.7.yml
1.16.7 will now be installed by default.
=> Updated Go to 1.16.7

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.17-arm64.yml, vars/versions/1.17-armv6l.yml, vars/versions/1.17.yml
1.17 will now be installed by default.
=> Updated Go to 1.17

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.17.1-arm64.yml, vars/versions/1.17.1-armv6l.yml, vars/versions/1.17.1.yml
1.17.1 will now be installed by default.
=> Updated Go to 1.17.1

README.md, meta/main.yml, molecule/debian-max/molecule.yml
Bullseye is the latest stable version of Debian.
=> Increased upper Debian test version to Bullseye

README.md, meta/main.yml, molecule/fedora/molecule.yml
=> Upgraded Fedora test version to 34

README.md, meta/main.yml, molecule/opensuse/molecule.yml
=> Upgraded openSUSE version to 15.2

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.17.3-arm64.yml, vars/versions/1.17.3-armv6l.yml, vars/versions/1.17.3.yml
1.17.3 will now be installed by default.
=> Updated Go to 1.17.3

README.md, meta/main.yml, molecule/default/molecule.yml, molecule/ubuntu-arm32v7/molecule.yml, molecule/ubuntu-arm64v8/molecule.yml, molecule/ubuntu-max-go-eol/molecule.yml
The latests LTS release of Ubuntu.
=> Increased upper Ubuntu test version to Focal

molecule/ubuntu-arm32v7/molecule.yml, molecule/ubuntu-arm64v8/molecule.yml
=> Fixed test ARM image names

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.17.4-arm64.yml, vars/versions/1.17.4-armv6l.yml, vars/versions/1.17.4.yml
1.17.4 will now be installed by default.
=> Updated Go to 1.17.4

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.17.5-arm64.yml, vars/versions/1.17.5-armv6l.yml, vars/versions/1.17.5.yml
1.17.5 will now be installed by default.
=> Updated Go to 1.17.5

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.17.6-arm64.yml, vars/versions/1.17.6-armv6l.yml, vars/versions/1.17.6.yml
1.17.6 will now be installed by default.
=> Updated Go to 1.17.6

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.17.7-arm64.yml, vars/versions/1.17.7-armv6l.yml, vars/versions/1.17.7.yml
1.17.7 will now be installed by default.
=> Updated Go to 1.17.7

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.17.8-arm64.yml, vars/versions/1.17.8-armv6l.yml, vars/versions/1.17.8.yml
1.17.8 will now be installed by default.
=> Updated Go to 1.17.8

README.md, meta/main.yml, molecule/fedora/molecule.yml
=> Upgraded Fedora test version to 35

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.18-arm64.yml, vars/versions/1.18-armv6l.yml, vars/versions/1.18.yml
1.18 will now be installed by default.
=> Updated Go to 1.18

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.18.1-arm64.yml, vars/versions/1.18.1-armv6l.yml, vars/versions/1.18.1.yml
1.18.1 will now be installed by default.
=> Updated Go to 1.18.1

.github/workflows/ci.yml
To make changing versions easier.
=> Added comments in workflow for Ansible versions

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.18.2-arm64.yml, vars/versions/1.18.2-armv6l.yml, vars/versions/1.18.2.yml
1.18.2 will now be installed by default.
=> Updated Go to 1.18.2

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.18.4-arm64.yml, vars/versions/1.18.4-armv6l.yml, vars/versions/1.18.4.yml
1.18.4 will now be installed by default.
=> Updated Go to 1.18.4

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.18.5-arm64.yml, vars/versions/1.18.5-armv6l.yml, vars/versions/1.18.5.yml
1.18.5 will now be installed by default.
=> Updated Go to 1.18.5

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.19-arm64.yml, vars/versions/1.19-armv6l.yml, vars/versions/1.19.yml
1.19 will now be installed by default.
=> Updated Go to 1.19

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.19.1-arm64.yml, vars/versions/1.19.1-armv6l.yml, vars/versions/1.19.1.yml
1.19.1 will now be installed by default.
=> Updated Go to 1.19.1

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.19.2-arm64.yml, vars/versions/1.19.2-armv6l.yml, vars/versions/1.19.2.yml
1.19.2 will now be installed by default.
=> Updated Go to 1.19.2

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.19.3-arm64.yml, vars/versions/1.19.3-armv6l.yml, vars/versions/1.19.3.yml
1.19.3 will now be installed by default.
=> Updated Go to 1.19.3

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.19.5-arm64.yml, vars/versions/1.19.5-armv6l.yml, vars/versions/1.19.5.yml
1.19.5 will now be installed by default.
=> Updated Go to 1.19.5

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.20-arm64.yml, vars/versions/1.20-armv6l.yml, vars/versions/1.20.yml
1.20 will now be installed by default.
=> Updated Go to 1.20

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.20.1-arm64.yml, vars/versions/1.20.1-armv6l.yml, vars/versions/1.20.1.yml
1.20.1 will now be installed by default.
=> Updated Go to 1.20.1

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.20.2-arm64.yml, vars/versions/1.20.2-armv6l.yml, vars/versions/1.20.2.yml
1.20.2 will now be installed by default.
=> Updated Go to 1.20.2

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.20.3-arm64.yml, vars/versions/1.20.3-armv6l.yml, vars/versions/1.20.3.yml
1.20.3 will now be installed by default.
=> Updated Go to 1.20.3

.yamllint, defaults/main.yml, meta/main.yml, molecule/default/converge.yml, molecule/ubuntu-max-go-eol/converge.yml, tasks/main.yml, vars/main.yml
In preparation for Molecule upgrade.
=> Fixed Ansible Lint warnings

.yamllint
Was giving warnings for GitHub workflows.
=> Fixed yamllint false positives

README.md, defaults/main.yml, molecule/debian-max/molecule.yml, molecule/debian-min/molecule.yml, molecule/default/converge.yml, molecule/default/molecule.yml, molecule/fedora/molecule.yml, molecule/opensuse/molecule.yml, molecule/rocky/molecule.yml, molecule/ubuntu-arm32v7/molecule.yml, molecule/ubuntu-arm64v8/molecule.yml, molecule/ubuntu-max-go-eol/molecule.yml, molecule/ubuntu-min/molecule.yml, tasks/main.yml
Support `inject_facts_as_vars: false`.
Fix: resolves #277
=> Removed dependency on facts injected as vars

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.20.5-arm64.yml, vars/versions/1.20.5-armv6l.yml, vars/versions/1.20.5.yml
1.20.5 will now be installed by default.
=> Updated Go to 1.20.5

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.20.6-arm64.yml, vars/versions/1.20.6-armv6l.yml, vars/versions/1.20.6.yml
1.20.6 will now be installed by default.
=> Updated Go to 1.20.6

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.20.7-arm64.yml, vars/versions/1.20.7-armv6l.yml, vars/versions/1.20.7.yml
1.20.7 will now be installed by default.
=> Updated Go to 1.20.7

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.21.0-arm64.yml, vars/versions/1.21.0-armv6l.yml, vars/versions/1.21.0.yml
1.21.0 will now be installed by default.
=> Updated Go to 1.21.0

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.21.1-arm64.yml, vars/versions/1.21.1-armv6l.yml, vars/versions/1.21.1.yml
1.21.1 will now be installed by default.
=> Updated Go to 1.21.1

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.21.2-arm64.yml, vars/versions/1.21.2-armv6l.yml, vars/versions/1.21.2.yml
1.21.2 will now be installed by default.
=> Updated Go to 1.21.2

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.21.3-arm64.yml, vars/versions/1.21.3-armv6l.yml, vars/versions/1.21.3.yml
1.21.3 will now be installed by default.
=> Updated Go to 1.21.3

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.21.4-arm64.yml, vars/versions/1.21.4-armv6l.yml, vars/versions/1.21.4.yml
1.21.4 will now be installed by default.
=> Updated Go to 1.21.4

meta/main.yml
For new Ansible Galaxy version.
=> Updated Galaxy metadata

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.21.5-arm64.yml, vars/versions/1.21.5-armv6l.yml, vars/versions/1.21.5.yml
1.21.5 will now be installed by default.
=> Updated Go to 1.21.5

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.21.6-arm64.yml, vars/versions/1.21.6-armv6l.yml, vars/versions/1.21.6.yml
1.21.6 will now be installed by default.
=> Updated Go to 1.21.6

README.md, meta/main.yml, molecule/opensuse/molecule.yml
=> Upgraded openSUSE version to 15.5

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.22.1-arm64.yml, vars/versions/1.22.1-armv6l.yml, vars/versions/1.22.1.yml
1.22.1 will now be installed by default.
=> Updated Go to 1.22.1

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.22.2-arm64.yml, vars/versions/1.22.2-armv6l.yml, vars/versions/1.22.2.yml
1.22.2 will now be installed by default.
=> Updated Go to 1.22.2

.github/workflows/ci.yml
=> Upgrade GitHub Actions to Ubuntu Jammy

README.md, meta/main.yml, molecule/default/molecule.yml, molecule/ubuntu-arm32v7/molecule.yml, molecule/ubuntu-arm64v8/molecule.yml, molecule/ubuntu-max-go-eol/molecule.yml
The old LTS release of Ubuntu.
=> Increased upper Ubuntu test version to Jammy

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.22.3-arm64.yml, vars/versions/1.22.3-armv6l.yml, vars/versions/1.22.3.yml
1.22.3 will now be installed by default.
=> Updated Go to 1.22.3

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.22.4-arm64.yml, vars/versions/1.22.4-armv6l.yml, vars/versions/1.22.4.yml
1.22.4 will now be installed by default.
=> Updated Go to 1.22.4

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.22.5-arm64.yml, vars/versions/1.22.5-armv6l.yml, vars/versions/1.22.5.yml
1.22.5 will now be installed by default.
=> Updated Go to 1.22.5

.gitignore
=> Added DevPod to .gitignore

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.22.6-arm64.yml, vars/versions/1.22.6-armv6l.yml, vars/versions/1.22.6.yml
1.22.6 will now be installed by default.
=> Updated Go to 1.22.6

go_versions_all.sh, go_versions_stable.sh
=> Added utility shell scripts

README.md, defaults/main.yml, molecule/default/tests/test_role.py, vars/versions/1.22.7-arm64.yml, vars/versions/1.22.7-armv6l.yml, vars/versions/1.22.7.yml
1.22.7 will now be installed by default.
=> Updated Go to 1.22.7

add_new_versions.py
=> Added version update script

requirements/ansible-max.txt, requirements/ansible-min.txt, requirements/dev.txt, requirements/molecule.in, requirements/molecule.txt
Keeping up with the latest changes.
=> Upgraded Molecule to version 24.9.0

.github/workflows/ci.yml, README.md, meta/main.yml, molecule/default/molecule.yml, molecule/ubuntu-arm32v7/molecule.yml, molecule/ubuntu-arm64v8/molecule.yml, molecule/ubuntu-max-go-eol/molecule.yml
The new LTS release of Ubuntu.
=> Increased upper Ubuntu test version to Noble

README.md, meta/main.yml, molecule/default/converge.yml, molecule/fedora/molecule.yml
=> Increased Fedora test version to 41

.github/workflows/ci.yml
=> Updated GitHub Actions to use native ARM runners
