gantsign/ansible-role-golang

- README.md
- vars/versions/1.8.4.yml
Go 1.9 will remain the default version installed.
> Added support for Go 1.8.4

- README.md
- vars/versions/1.9.5.yml
Go 1.10 will remain the default version installed.
> Added support for Go 1.9.5

- tasks/main.yml
Because of the need to strip the top level directory we were using `tar` directly. Now we've increased the minimum Ansible version to 2.3, we can use the `extra_opts` option of the `unarchive` module instead.
> Changed from tar command to unarchive module

- vars/versions/1.9.7.yml
Go 1.10.2 will remain the default version installed.
> Added support for Go 1.9.7

- tasks/main.yml
It can reasonably be expected to be present. It was only added due to an earlier version of Molecule.
> Removed unnecessary ca-certificates install

- tasks/main.yml
```
[DEPRECATION WARNING]: Invoking "zypper" only once while using a loop via
squash_actions is deprecated. Instead of using a loop to supply multiple items
and specifying `name: {{ item }}`, please use `name: [u'gzip', u'tar']` and
remove the loop. This feature will be removed in version 2.11. Deprecation
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```
> Resolved zypper module syntax deprecation warning

- README.md
- vars/versions/1.11.6.yml
Go 1.12 will remain the default version installed.
> Added support for Go 1.11.6

- README.md
- molecule/ubuntu-max-go-eol/playbook.yml
- molecule/ubuntu-max-go-eol/tests/test_role.py
- vars/versions/1.12.10.yml
Go 1.13 remains the default version installed.
> Added support for Go 1.12.10

- README.md
- meta/main.yml
- molecule/ubuntu-min/molecule.yml
Canonical have ended standard support for Ubuntu Trusty (14.04).
> Dropped support for Ubuntu Trusty

- .travis.yml
`jobs` is the new preferred name.
> Updated Travis CI to use jobs key instead of matrix

- vars/versions/1.14.1-aarch64.yml
Was using the amd64 sha256 by mistake.
> Fixed sha256 for 1.14.1 arm64

- vars/main-armv7l.yml
- vars/versions/1.14.10-armv71.yml
- vars/versions/1.15.3-armv7l.yml
RPiOS 32bit reports ansible_architecture as armv7l, which requires golang linux-armv6l builds. Tested on a Raspberry Pi 4b.
I've not updated the README because I didn't know what you'd want to add there. I saw there was a previous PR which added support for all versions for arm64, which means the Advanced Configuration section could be changed because that example doesn't need to be for arm64 anymore as that's natively supported.
> Add support for current gloang releases on 32bit RPiOS

- README.md
- meta/main.yml
- molecule/centos-min/molecule.yml
CentOS ended support for 6 on 2020-11-30.
> Upgraded minimum CentOS  version to 7

- README.md
- meta/main.yml
- molecule/debian-min/molecule.yml
Ansible 2.10 requires Python 3.5
> Dropped support for Debian Jessie

- molecule/ubuntu-max-go-eol/converge.yml
- molecule/ubuntu-max-go-eol/tests/test_role.py
Go 1.17 remains the default version installed.
> Added support for Go 1.16.7

- .github/workflows/ci.yml
> Upgraded minimum Ansible test version to 2.9.26

- README.md
- defaults/main.yml
- molecule/default/tests/test_role.py
- vars/versions/1.18.3-arm64.yml
- vars/versions/1.18.3-armv6l.yml
- vars/versions/1.18.3.yml
1.18.3 will now be installed by default.
> Updated Go to 1.18.3

- molecule/ubuntu-max-go-eol/converge.yml
- molecule/ubuntu-max-go-eol/tests/test_role.py
Go 1.19 remains the default version installed.
> Updated EOL tests to Go 1.18.5

- templates/golang.sh.j2
To give it higher precedence than the Go installation from OS packages.
> Moved Go installation to start of PATH

- .github/workflows/ci.yml
- README.md
- meta/main.yml
- molecule/debian-min/molecule.yml
Debian standard support ended on 01 Jul 2022.
> Dropped support for Debian Stretch

- README.md
Since 3.2.2 the role is published under a different name on Galaxy. It's not mentioned in the release notes, so I'm not sure that's intentional.
I also updated the link to the role catalog.
> Fix link to galaxy and role name change

- README.md
- molecule/ubuntu-max-go-eol/converge.yml
- molecule/ubuntu-max-go-eol/tests/test_role.py
- vars/versions/1.21.7-arm64.yml
- vars/versions/1.21.7-armv6l.yml
- vars/versions/1.21.7.yml
Go 1.22.0 remains the default version installed.
> Added support for Go 1.21.7

- README.md
- meta/main.yml
- molecule/debian-max/molecule.yml
Bookworm is the latest stable version of Debian.
> Increased upper Debian test version to Bookworm

- molecule/ubuntu-arm32v7/molecule.yml
- molecule/ubuntu-arm64v8/molecule.yml
Prefixing the image name with the architecture no longer works.
> Fixed ARM Molecule tests

- requirements/ansible-max.txt
- requirements/ansible-min.txt
- requirements/dev.txt
- requirements/molecule.in
- requirements/molecule.txt
It's no longer needed now we've upgraded Molecule.
> Removed PyTest 8 workaround

- README.md
- meta/main.yml
- molecule/opensuse/molecule.yml
Leap defaults to Python 3.6, which is too old for recent Ansible versions.
> Changed openSUSE tests to use Tumbleweed

- requirements/ansible-max.in
- requirements/ansible-max.txt
- requirements/dev.txt
Ensure this role works with Ansible Core 2.17.6.
> Increased upper Ansible Core test range to 2.17.6

- README.md
- meta/main.yml
- molecule/ubuntu-min/molecule.yml
Canonical have ended standard support for Ubuntu Focal.
> Dropped support for Ubuntu Focal

- README.md
- meta/main.yml
- molecule/debian-min/molecule.yml
Debian standard support ended on 30 Jun 2025.
> Dropped support for Debian Buster

- molecule/default/converge.yml
We're no longer testing with Ubuntu 20.04.
> Removed obsolete cert rehashing workaround

- README.md
- defaults/main.yml
- molecule/default/tests/test_role.py
- molecule/ubuntu-max-go-eol/converge.yml
- molecule/ubuntu-max-go-eol/tests/test_role.py
- vars/versions/1.22.8-amd64.yml
- vars/versions/1.22.8-arm64.yml
- vars/versions/1.22.8-armv6l.yml
- vars/versions/1.22.9-amd64.yml
- vars/versions/1.22.9-arm64.yml
- vars/versions/1.22.9-armv6l.yml
- vars/versions/1.23.0-amd64.yml
- vars/versions/1.23.0-arm64.yml
- vars/versions/1.23.0-armv6l.yml
- vars/versions/1.23.1-amd64.yml
- vars/versions/1.23.1-arm64.yml
- vars/versions/1.23.1-armv6l.yml
- vars/versions/1.23.2-amd64.yml
- vars/versions/1.23.2-arm64.yml
- vars/versions/1.23.2-armv6l.yml
- vars/versions/1.23.3-amd64.yml
- vars/versions/1.23.3-arm64.yml
- vars/versions/1.23.3-armv6l.yml
1.23.3 will now be installed by default.
Support for the following versions has also been added:
* `1.23.2`
* `1.23.1`
* `1.23.0`
* `1.22.9`
* `1.22.8`
> Updated Go to 1.23.3
